/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrackerRouteImport } from './routes/_app.tracker'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppLeaveRouteImport } from './routes/_app.leave'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAdminReportsRouteImport } from './routes/_app.admin.reports'
import { Route as AppAdminLeaveRouteImport } from './routes/_app.admin.leave'
import { Route as AppAdminEmployeesRouteImport } from './routes/_app.admin.employees'
import { Route as AppAdminAttendanceRouteImport } from './routes/_app.admin.attendance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrackerRoute = AppTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLeaveRoute = AppAdminLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminEmployeesRoute = AppAdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAttendanceRoute = AppAdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/leave': typeof AppLeaveRoute
  '/reports': typeof AppReportsRoute
  '/tracker': typeof AppTrackerRoute
  '/admin/attendance': typeof AppAdminAttendanceRoute
  '/admin/employees': typeof AppAdminEmployeesRoute
  '/admin/leave': typeof AppAdminLeaveRoute
  '/admin/reports': typeof AppAdminReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/leave': typeof AppLeaveRoute
  '/reports': typeof AppReportsRoute
  '/tracker': typeof AppTrackerRoute
  '/admin/attendance': typeof AppAdminAttendanceRoute
  '/admin/employees': typeof AppAdminEmployeesRoute
  '/admin/leave': typeof AppAdminLeaveRoute
  '/admin/reports': typeof AppAdminReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/leave': typeof AppLeaveRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/tracker': typeof AppTrackerRoute
  '/_app/admin/attendance': typeof AppAdminAttendanceRoute
  '/_app/admin/employees': typeof AppAdminEmployeesRoute
  '/_app/admin/leave': typeof AppAdminLeaveRoute
  '/_app/admin/reports': typeof AppAdminReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/leave'
    | '/reports'
    | '/tracker'
    | '/admin/attendance'
    | '/admin/employees'
    | '/admin/leave'
    | '/admin/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/leave'
    | '/reports'
    | '/tracker'
    | '/admin/attendance'
    | '/admin/employees'
    | '/admin/leave'
    | '/admin/reports'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/leave'
    | '/_app/reports'
    | '/_app/tracker'
    | '/_app/admin/attendance'
    | '/_app/admin/employees'
    | '/_app/admin/leave'
    | '/_app/admin/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tracker': {
      id: '/_app/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AppTrackerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave': {
      id: '/_app/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/leave': {
      id: '/_app/admin/leave'
      path: '/leave'
      fullPath: '/admin/leave'
      preLoaderRoute: typeof AppAdminLeaveRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/employees': {
      id: '/_app/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AppAdminEmployeesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/attendance': {
      id: '/_app/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AppAdminAttendanceRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAttendanceRoute: typeof AppAdminAttendanceRoute
  AppAdminEmployeesRoute: typeof AppAdminEmployeesRoute
  AppAdminLeaveRoute: typeof AppAdminLeaveRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAttendanceRoute: AppAdminAttendanceRoute,
  AppAdminEmployeesRoute: AppAdminEmployeesRoute,
  AppAdminLeaveRoute: AppAdminLeaveRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTrackerRoute: typeof AppTrackerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppReportsRoute: AppReportsRoute,
  AppTrackerRoute: AppTrackerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
